### PR TITLE
Add users.identity method

### PR DESCRIPTION
**Pull request by metaodi**
See https://api.slack.com/methods/users.identity

### CODE REVIEW

**Comment by metaodi** [comment]
@Ustice do you need a test or a documentation change as well or is this change sufficient?

**Comment by Ustice** [comment]
There are a number of errors that are missing. Would you mind adding those in too?

**Comment by metaodi** [comment]
I thought those were omitted on purpose, as they are on all (most?) other methods as well.

**Comment by Ustice** [comment]
Never mind, you are right. If I remember right, I have a special catch for those.

**Comment by metaodi** [comment]
@Ustice thanks! Do you publish a new release on npm?

**Pull request merged**
