### PR TITLE
Update all packages and adapt name of superagent field

### LINKED ISSUE #16: Fix qs vulnerability by updating superagent
[According to snyk](https://snyk.io/test/npm/slack-api/0.1.12) this module has a dependency on `superagent,` which in turn has a dependency on a vulnerable version of the `qs` module.

I think to update superagent in this project would make sense, I'll open a PR for it.

### PR DESCRIPTION
**Pull request by metaodi**
Fixes #16

### CODE REVIEW

**Comment by metaodi** [comment]
@Ustice what do you think?

**Comment by Ustice** [comment]
👍 Good call. Sorry, I haven't been watching this project much lately.

**Comment by metaodi** [comment]
@Ustice would you mind creating a new release containing this fix? Thanks in advance.

**Comment by Ustice** [comment]
@metaodi Done. Thanks for the suggestion.

**Pull request merged**
